version: '3'

services:
    traefik:
        container_name: traefik
        image: traefik:1.7
        restart: ${DOCKER_RESTART}
        command: -c /dev/null --api --docker --configFile=/etc/traefik/traefik.toml --debug
        networks:
            - reverse_proxy
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik:/etc/traefik
            - ./certs/:/certs/
        labels:
            - "traefik.port=8080"
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:traefik.${DOCKER_TLD}"
            - "traefik.backend=traefik"
            - "traefik.backend.loadbalancer.sticky=true"

networks:
    reverse_proxy:
        # Expose to local network
        external: true
