version: '2'

services:
    traefik:
        container_name: traefik
        image: traefik:latest
        restart: ${DOCKER_RESTART}
        command: -c /dev/null --api --docker --configFile=/etc/traefik/traefik.toml --debug
        networks:
            - reverse_proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/etc/traefik/traefik.toml
        labels:
            - "traefik.frontend.priority=2"
            - "traefik.backend=traefik"
            - "traefik.port=8080"
            - 'traefik.enable=true'
            - "traefik.docker.network=reverse_proxy"
            - "traefik.frontend.rule=Host:traefik.${DOCKER_TLD}"
            - "traefik.frontend.passHostHeader=true"
            - "traefik.backend.loadbalancer.sticky=true"

networks:
    reverse_proxy:
        # Expose to local network
        external: true
